name: plan
on:
  pull_request:
  push:
  schedule:
    - cron: "11 21 * * *"
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - uses: hashicorp/setup-terraform@v1
      - run: gem install rake
      - run: rake terraform:plan
        env:
          AWS_ACCESS_KEY_ID:               ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION:              ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY:           ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_SLACK_CLIENT_ID:          ${{ secrets.SLACK_CLIENT_ID }}
          TF_VAR_SLACK_CLIENT_SECRET:      ${{ secrets.SLACK_CLIENT_SECRET }}
          TF_VAR_SLACK_OAUTH_ERROR_URI:    ${{ secrets.SLACK_OAUTH_ERROR_URI }}
          TF_VAR_SLACK_OAUTH_REDIRECT_URI: ${{ secrets.SLACK_OAUTH_REDIRECT_URI }}
          TF_VAR_SLACK_OAUTH_SUCCESS_URI:  ${{ secrets.SLACK_OAUTH_SUCCESS_URI }}
          TF_VAR_SLACK_SIGNING_SECRET:     ${{ secrets.SLACK_SIGNING_SECRET }}
          TF_VAR_SLACK_SIGNING_VERSION:    ${{ secrets.SLACK_SIGNING_VERSION }}
          TF_VAR_SLACK_TOKEN:              ${{ secrets.SLACK_TOKEN }}
